USER_NAME: "YOUR_APPLE_ID_EMAIL"
ALBUM_NAME: "All Photos"      
TEMP_FOLDER: "media-temp" 
MEDIA_FOLDER: "media" 
RECENT_PHOTOS: 200              
MAX_MEDIA_STORED: 500            
MAX_MEDIA_SIZE_GB: 1     
